### PR TITLE
fix path to config.vm.box

### PR DESCRIPTION
**Pull request by moy**
Without this, Vagrant fails to download the box. The box is
documented at https://atlas.hashicorp.com/nrel/boxes/CentOS-6.5-x86_64

### CODE REVIEW

**Comment by roidelapluie** [comment]
How can we trust nrel versus the official centos boxes?

**Comment by moy** [comment]
I don't understand what's supposed to happen, but without my patch the Vagrantfile does not work at all:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'CentOS-6.5-x86_64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'CentOS-6.5-x86_64' (v0) for provider: virtualbox
    default: Downloading: CentOS-6.5-x86_64
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file .../vagrant-gerrit/CentOS-6.5-x86_64
```

I don't know if there's a better solution than my patch.

**Comment by roidelapluie** [comment]
I would leave people the choice of their box provider.

You can do a "vagrant box add CentOS-6.5-x86_64 nrel/CentOS-6.5-x86_64" to get that box if you want to use the one from nrel.

**Comment by moy** [comment]
This does not work for me:

```
$ vagrant box add CentOS-6.5-x86_64 nrel/CentOS-6.5-x86_64
==> box: Loading metadata for box 'nrel/CentOS-6.5-x86_64'
    box: URL: https://atlas.hashicorp.com/nrel/CentOS-6.5-x86_64
The box you're adding has a name different from the name you
requested. For boxes with metadata, you cannot override the name.
If you're adding a box using `vagrant box add`, don't specify
the `--name` parameter. If the box is being added via a Vagrantfile,
change the `config.vm.box` value to match the name below.

Requested name: CentOS-6.5-x86_64
Actual name: nrel/CentOS-6.5-x86_64
```

How are you using this Vagrant file? I didn't find a way to use it without modifying config.vm.box inside the Vagrant file. There's probably one (I'm far from being a Vagrant expert), but I'd like to find it and then send a documentation pull-request instead of this one.

(BTW, thanks a lot for this vagrant-gerrit. Even though it did not work out of the box for me, it did help me a lot! I used it to test the Gerrit environment for [git-multimail](https://github.com/git-multimail/git-multimail))

**Comment by roidelapluie** [comment]
I have chosen to use a vagrant box from one of my colleagues. Thanks for your input!!

**Pull request closed without merging**
